### ISSUE TITLE
启用模块后所有视频都没弹幕

### ISSUE THREAD

**Issue by HCLonely** [kosaka-bun/Qingxin#1]
Android 10
MIUI 12.5.2稳定版
哔哩哔哩 6.53.0

什么规则都没启用
![83b80894b1b51a339d3a2c0e4a29b3e](https://user-images.githubusercontent.com/26346802/147084374-bfc5105b-50a7-4ab0-bc8f-d213490a84f5.jpg)

LSP 1.6.5 日志
```
[ 2021-12-22T19:09:31.884    10226: 18295: 18295 I/LSPosed-Bridge  ] Loading module de.honoka.android.xposed.qingxin from /data/app/de.honoka.android.xposed.qingxin-gfk_hJXkpaE6LmnmupTvfA==/base.apk
[ 2021-12-22T19:09:31.985    10226: 18295: 18295 I/LSPosed-Bridge  ]   Loading class de.honoka.android.xposed.qingxin.xposed.XposedMain
[ 2021-12-22T19:09:32.154    10226: 18295: 18295 I/LSPosed-Bridge  ] 
hook加载完成
[ 2021-12-22T19:09:33.006    10226: 18295: 18295 I/LSPosed-Bridge  ] 
得到Application对象，开始加载配置与规则
[ 2021-12-22T19:09:33.075    10226: 18295: 18442 I/LSPosed-Bridge  ] 
MainPreference(blockAllMainPagePublicity=false, blockAllHotSearchWords=false, convertAllVerticalAv=false, showBlockLog=false, toastOnBlock=false, testMode=true, blockRecommendedTopics=false, disablePlayerLongPress=false)
[ 2021-12-22T19:09:33.079    10226: 18295: 18442 I/LSPosed-Bridge  ] 
清心模块加载成功
[ 2021-12-22T19:09:33.227    10226: 18295: 18400 I/LSPosed-Bridge  ] 
java.lang.IllegalStateException: Not a JSON Object: 433351
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at de.honoka.android.xposed.qingxin.xposed.filter.HotSearchFilter.apply(HotSearchFilter.java:28)
	at de.honoka.android.xposed.qingxin.xposed.filter.HotSearchFilter.apply(HotSearchFilter.java:20)
	at de.honoka.android.xposed.qingxin.xposed.hook.JsonHook.handleJson(JsonHook.java:68)
	at de.honoka.android.xposed.qingxin.xposed.hook.JsonHook.before(JsonHook.java:53)
	at de.honoka.android.xposed.qingxin.xposed.hook.LateInitHook.beforeHookedMethod(LateInitHook.java:17)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.constructor(Unknown Source:18)
	at com.alibaba.fastjson.parser.DefaultJSONParser.<init>(BL:3)
	at com.alibaba.fastjson.JSON.parseObject(BL:13)
	at com.bilibili.okretro.converter.b.convert(BL:3)
	at com.bilibili.okretro.converter.b.convert(BL:1)
	at com.bilibili.okretro.converter.c.a(BL:8)
	at com.bilibili.okretro.converter.c.convert(BL:1)
	at com.bilibili.okretro.call.BiliCall.q(BL:8)
	at com.bilibili.okretro.call.BiliCall.execute(BL:14)
	at com.bilibili.bplus.im.api.c.B(BL:1)
	at w1.g.j.d.b.b.i.u0.k(BL:1)
	at w1.g.j.d.b.b.i.u0.f(BL:3)
	at w1.g.j.d.b.b.c$b.run(BL:20)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.bilibili.droid.thread.e.run(BL:5)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
[ 2021-12-22T19:09:33.520    10226: 18492: 18492 I/LSPosed-Bridge  ] Loading module de.honoka.android.xposed.qingxin from /data/app/de.honoka.android.xposed.qingxin-gfk_hJXkpaE6LmnmupTvfA==/base.apk
[ 2021-12-22T19:09:33.625    10226: 18492: 18492 I/LSPosed-Bridge  ]   Loading class de.honoka.android.xposed.qingxin.xposed.XposedMain
[ 2021-12-22T19:09:33.649    10226: 18511: 18511 I/LSPosed-Bridge  ] Loading module de.honoka.android.xposed.qingxin from /data/app/de.honoka.android.xposed.qingxin-gfk_hJXkpaE6LmnmupTvfA==/base.apk
[ 2021-12-22T19:09:33.738    10226: 18535: 18535 I/LSPosed-Bridge  ] Loading module de.honoka.android.xposed.qingxin from /data/app/de.honoka.android.xposed.qingxin-gfk_hJXkpaE6LmnmupTvfA==/base.apk
[ 2021-12-22T19:09:33.750    10226: 18511: 18511 I/LSPosed-Bridge  ]   Loading class de.honoka.android.xposed.qingxin.xposed.XposedMain
[ 2021-12-22T19:09:33.770    10226: 18492: 18492 I/LSPosed-Bridge  ] 
hook加载完成
[ 2021-12-22T19:09:33.843    10226: 18535: 18535 I/LSPosed-Bridge  ]   Loading class de.honoka.android.xposed.qingxin.xposed.XposedMain
[ 2021-12-22T19:09:33.931    10226: 18511: 18511 I/LSPosed-Bridge  ] 
hook加载完成
[ 2021-12-22T19:09:33.988    10226: 18535: 18535 I/LSPosed-Bridge  ] 
hook加载完成
[ 2021-12-22T19:09:34.235    10226: 18492: 18492 I/LSPosed-Bridge  ] 
得到Application对象，开始加载配置与规则
[ 2021-12-22T19:09:34.368    10226: 18511: 18511 I/LSPosed-Bridge  ] 
得到Application对象，开始加载配置与规则
[ 2021-12-22T19:09:34.410    10226: 18535: 18535 I/LSPosed-Bridge  ] 
得到Application对象，开始加载配置与规则
[ 2021-12-22T19:09:34.415    10226: 18492: 18635 I/LSPosed-Bridge  ] 
MainPreference(blockAllMainPagePublicity=false, blockAllHotSearchWords=false, convertAllVerticalAv=false, showBlockLog=false, toastOnBlock=false, testMode=true, blockRecommendedTopics=false, disablePlayerLongPress=false)
[ 2021-12-22T19:09:34.417    10226: 18492: 18635 I/LSPosed-Bridge  ] 
清心模块加载成功
[ 2021-12-22T19:09:34.596    10226: 18535: 18674 I/LSPosed-Bridge  ] 
MainPreference(blockAllMainPagePublicity=false, blockAllHotSearchWords=false, convertAllVerticalAv=false, showBlockLog=false, toastOnBlock=false, testMode=true, blockRecommendedTopics=false, disablePlayerLongPress=false)
[ 2021-12-22T19:09:34.598    10226: 18535: 18674 I/LSPosed-Bridge  ] 
清心模块加载成功
[ 2021-12-22T19:09:34.630    10226: 18511: 18653 I/LSPosed-Bridge  ] 
MainPreference(blockAllMainPagePublicity=false, blockAllHotSearchWords=false, convertAllVerticalAv=false, showBlockLog=false, toastOnBlock=false, testMode=true, blockRecommendedTopics=false, disablePlayerLongPress=false)
[ 2021-12-22T19:09:34.633    10226: 18511: 18653 I/LSPosed-Bridge  ] 
清心模块加载成功
[ 2021-12-22T19:09:45.633    10226: 19089: 19089 I/LSPosed-Bridge  ] Loading module de.honoka.android.xposed.qingxin from /data/app/de.honoka.android.xposed.qingxin-gfk_hJXkpaE6LmnmupTvfA==/base.apk
[ 2021-12-22T19:09:45.800    10226: 19089: 19089 I/LSPosed-Bridge  ]   Loading class de.honoka.android.xposed.qingxin.xposed.XposedMain
[ 2021-12-22T19:09:45.988    10226: 19089: 19089 I/LSPosed-Bridge  ] 
hook加载完成
[ 2021-12-22T19:09:47.079    10226: 19089: 19089 I/LSPosed-Bridge  ] 
得到Application对象，开始加载配置与规则
[ 2021-12-22T19:09:47.220    10226: 19089: 19221 I/LSPosed-Bridge  ] 
MainPreference(blockAllMainPagePublicity=false, blockAllHotSearchWords=false, convertAllVerticalAv=false, showBlockLog=false, toastOnBlock=false, testMode=true, blockRecommendedTopics=false, disablePlayerLongPress=false)
[ 2021-12-22T19:09:47.223    10226: 19089: 19221 I/LSPosed-Bridge  ] 
清心模块加载成功
[ 2021-12-22T19:09:50.536    10226: 19089: 19089 I/LSPosed-Bridge  ] 
WebView调试已开启
[ 2021-12-22T19:10:30.148    10226: 19815: 19815 I/LSPosed-Bridge  ] Loading module de.honoka.android.xposed.qingxin from /data/app/de.honoka.android.xposed.qingxin-gfk_hJXkpaE6LmnmupTvfA==/base.apk
[ 2021-12-22T19:10:30.244    10226: 19815: 19815 I/LSPosed-Bridge  ]   Loading class de.honoka.android.xposed.qingxin.xposed.XposedMain
[ 2021-12-22T19:10:30.404    10226: 19815: 19815 I/LSPosed-Bridge  ] 
hook加载完成
[ 2021-12-22T19:10:31.124    10226: 19815: 19815 I/LSPosed-Bridge  ] 
得到Application对象，开始加载配置与规则
[ 2021-12-22T19:10:31.198    10226: 19815: 20003 I/LSPosed-Bridge  ] 
MainPreference(blockAllMainPagePublicity=false, blockAllHotSearchWords=false, convertAllVerticalAv=false, showBlockLog=false, toastOnBlock=false, testMode=true, blockRecommendedTopics=false, disablePlayerLongPress=false)
[ 2021-12-22T19:10:31.201    10226: 19815: 20003 I/LSPosed-Bridge  ] 
清心模块加载成功
[ 2021-12-22T19:10:31.425    10226: 20039: 20039 I/LSPosed-Bridge  ] Loading module de.honoka.android.xposed.qingxin from /data/app/de.honoka.android.xposed.qingxin-gfk_hJXkpaE6LmnmupTvfA==/base.apk
[ 2021-12-22T19:10:31.556    10226: 20039: 20039 I/LSPosed-Bridge  ]   Loading class de.honoka.android.xposed.qingxin.xposed.XposedMain
[ 2021-12-22T19:10:31.576    10226: 19815: 19936 I/LSPosed-Bridge  ] 
java.lang.IllegalStateException: Not a JSON Object: 433351
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at de.honoka.android.xposed.qingxin.xposed.filter.HotSearchFilter.apply(HotSearchFilter.java:28)
	at de.honoka.android.xposed.qingxin.xposed.filter.HotSearchFilter.apply(HotSearchFilter.java:20)
	at de.honoka.android.xposed.qingxin.xposed.hook.JsonHook.handleJson(JsonHook.java:68)
	at de.honoka.android.xposed.qingxin.xposed.hook.JsonHook.before(JsonHook.java:53)
	at de.honoka.android.xposed.qingxin.xposed.hook.LateInitHook.beforeHookedMethod(LateInitHook.java:17)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.constructor(Unknown Source:18)
	at com.alibaba.fastjson.parser.DefaultJSONParser.<init>(BL:3)
	at com.alibaba.fastjson.JSON.parseObject(BL:13)
	at com.bilibili.okretro.converter.b.convert(BL:3)
	at com.bilibili.okretro.converter.b.convert(BL:1)
	at com.bilibili.okretro.converter.c.a(BL:8)
	at com.bilibili.okretro.converter.c.convert(BL:1)
	at com.bilibili.okretro.call.BiliCall.r(BL:17)
	at com.bilibili.okretro.call.BiliCall.execute(BL:46)
	at com.bilibili.bplus.im.api.c.B(BL:1)
	at w1.g.j.d.b.b.i.u0.k(BL:1)
	at w1.g.j.d.b.b.i.u0.f(BL:3)
	at w1.g.j.d.b.b.c$b.run(BL:20)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.bilibili.droid.thread.e.run(BL:5)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
[ 2021-12-22T19:10:31.697    10226: 20066: 20066 I/LSPosed-Bridge  ] Loading module de.honoka.android.xposed.qingxin from /data/app/de.honoka.android.xposed.qingxin-gfk_hJXkpaE6LmnmupTvfA==/base.apk
[ 2021-12-22T19:10:31.760    10226: 20039: 20039 I/LSPosed-Bridge  ] 
hook加载完成
[ 2021-12-22T19:10:31.825    10226: 20097: 20097 I/LSPosed-Bridge  ] Loading module de.honoka.android.xposed.qingxin from /data/app/de.honoka.android.xposed.qingxin-gfk_hJXkpaE6LmnmupTvfA==/base.apk
[ 2021-12-22T19:10:31.857    10226: 20066: 20066 I/LSPosed-Bridge  ]   Loading class de.honoka.android.xposed.qingxin.xposed.XposedMain
[ 2021-12-22T19:10:31.954    10226: 20097: 20097 I/LSPosed-Bridge  ]   Loading class de.honoka.android.xposed.qingxin.xposed.XposedMain
[ 2021-12-22T19:10:32.005    10226: 20066: 20066 I/LSPosed-Bridge  ] 
hook加载完成
[ 2021-12-22T19:10:32.119    10226: 20097: 20097 I/LSPosed-Bridge  ] 
hook加载完成
[ 2021-12-22T19:10:32.461    10226: 20066: 20066 I/LSPosed-Bridge  ] 
得到Application对象，开始加载配置与规则
[ 2021-12-22T19:10:32.481    10226: 20039: 20039 I/LSPosed-Bridge  ] 
得到Application对象，开始加载配置与规则
[ 2021-12-22T19:10:32.709    10226: 20039: 20236 I/LSPosed-Bridge  ] 
MainPreference(blockAllMainPagePublicity=false, blockAllHotSearchWords=false, convertAllVerticalAv=false, showBlockLog=false, toastOnBlock=false, testMode=true, blockRecommendedTopics=false, disablePlayerLongPress=false)
[ 2021-12-22T19:10:32.714    10226: 20039: 20236 I/LSPosed-Bridge  ] 
清心模块加载成功
[ 2021-12-22T19:10:32.729    10226: 20066: 20232 I/LSPosed-Bridge  ] 
MainPreference(blockAllMainPagePublicity=false, blockAllHotSearchWords=false, convertAllVerticalAv=false, showBlockLog=false, toastOnBlock=false, testMode=true, blockRecommendedTopics=false, disablePlayerLongPress=false)
[ 2021-12-22T19:10:32.731    10226: 20066: 20232 I/LSPosed-Bridge  ] 
清心模块加载成功
[ 2021-12-22T19:10:32.747    10226: 20097: 20097 I/LSPosed-Bridge  ] 
得到Application对象，开始加载配置与规则
[ 2021-12-22T19:10:32.835    10226: 20097: 20268 I/LSPosed-Bridge  ] 
MainPreference(blockAllMainPagePublicity=false, blockAllHotSearchWords=false, convertAllVerticalAv=false, showBlockLog=false, toastOnBlock=false, testMode=true, blockRecommendedTopics=false, disablePlayerLongPress=false)
[ 2021-12-22T19:10:32.837    10226: 20097: 20268 I/LSPosed-Bridge  ] 
清心模块加载成功
```

**Comment by kosaka-bun** [comment]
6.53.0版本对弹幕渲染逻辑进行了较大修改，原有方案已不能满足要求，现暂时搁置弹幕拦截功能。
请下载最新版本的模块，除弹幕拦截外，其他功能可正常使用，弹幕亦可正常显示。
